library(shiny)
library(leaflet)
library(dplyr)
library(shiny)
library(devtools)
library(ggmap)
library(ggplot2)
devtools::install_github("nourqweder/RAPI", subdir="RAPI", quiet = TRUE)
library(geoloc)
df <- readRDS("./sample_data.rds")